### ISSUE TITLE
Setup doesn't work

### ISSUE THREAD

**Issue by stuaxo** [shoebot/jupyter-shoebot#10]
I think the default setup that jupyter-pip suggests doesn't work (jupyter-cairo is also broken).

pip doesn't provide a stable api, so I guess it's not too surprising the ```pip.main``` doesn't work... have a vague memory of looking at it and thinking 🤔 in jupyter-cairo.

**Comment by rlafuente** [comment]
I've tried it in a test virtualenv and it worked -- what went wrong on your side exactly?

**Comment by stuaxo** [comment]
It couldn't find pip.main ... I think they must have moved it :(

pip is version 10.0

I think they only guarantee the commandline interface, not the internals with pip.

I need to have more of a play, because when I do get it installed, the kernel can't import shoebot.

**Comment by rlafuente** [comment]
Odd, I did get that error but I think it went away after doing `pip install jupyter-pip`

I did try this with pip 9. However I've just made a fresh virtualenv (running pip10) and it works with the following steps:

```bash
# install shoebot from jupyter branch
cd shoebot
git checkout jupyter
python setup.py install
# install jupyter
pip install jupyter jupyter-pip
# install the extension
cd ../jupyter-shoebot
python setup.py install
```

Can you try this and see if it goes through?

**Comment by stuaxo** [comment]
That worked, but then I had trouble with imports.

It might be because I'm using zsh and some plugin that tries to change the virtualenv when you move directory, I'll have another go later.

**Comment by rlafuente** [comment]
Just checked and can confirm that the error that it can't find `pip.main` can be fixed by installing `jupyter-pip`. (at least on my system!)

FWIW I'm also on zsh and running simple virtualenvwrapper. I did miss one step in my previous comment -- `jupyter kernelspec install shoebot_kernel --sys-prefix` (I've edited the comment above to reflect this). 

On this command, I've just noticed that the install docs mentioned the `--user` flag (put stuff in $HOME/.local) instead of `--sys-prefix` (put stuff in Py prefix, for virtualenvs), just fixed it.. Maybe that was the hitch in your case?

**Comment by stuaxo** [comment]
I was using --user     

I like to avoid installing stuff in the system python though (python is my day job, so I like to leave the system python unmolested and use virtualenvs for everything) - is there a way to do it without --sys-prefix.

**Comment by rlafuente** [comment]
You should use `--sys-prefix` for virtualenvs, since the prefix becomes the virtualenv's when you activate it, it's exactly for use cases like yours

**Comment by stuaxo** [comment]
That's what I thought it should do, but it was complaining about not being able to write to /usr, I'll try again later.

**Comment by stuaxo** [comment]
Seems to work for me with --sys-prefix, closing :)
