### ISSUE TITLE
jupyter kernelspec install shoebot_kernel --sys-prefix did not work for me

### ISSUE THREAD

**Issue by villares** [shoebot/jupyter-shoebot#15]
Following the docs at https://docs.shoebot.net/advanced.html#running-in-jupyter

`jupyter kernelspec install shoebot_kernel --sys-prefix`

```
[Errno 13] Permission denied: '/usr/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
```
then with `sudo`
```
Traceback (most recent call last):
  File "/home/villares/.local/bin/jupyter", line 5, in <module>
    from jupyter_core.command import main
ModuleNotFoundError: No module named 'jupyter_core'

```
I'm running on a conda environment

**Comment by stuaxo** [comment]
Try with --user maybe.   It looks like system installed jupyter `/usr/share/jupyter` is getting confused with another copy (I guess installed by conda??) at `/home/villares/.local/bin/jupyter`.

You could try using `--user` as it suggests, instead of `--sys-prefix` ?

I'm not a Conda user, so there's a bit of guesswork here.

**Comment by villares** [comment]
```
(lab) [villares@L340 jupyter-shoebot]$ jupyter kernelspec install shoebot_kernel --user
[InstallKernelSpec] Installed kernelspec shoebot_kernel in /home/villares/.local/share/jupyter/kernels/shoebot_kernel
```
![image](https://user-images.githubusercontent.com/3694604/111778433-65895080-8893-11eb-9154-1c51654e3da7.png)
